apiVersion: v2
dependencies:
    - name: common
      repository: '@chartrepo'
      version: 1.0.87
    - name: turbo-payment-service
      repository: '@chartrepo'
      version: 1.0.10
description: sample-payments application services for turbo apps
name: sample-payments
version: 1.0.65
