payment-management:
    enabled: true
    image:
        pullPolicy: Always
        repository: 012345678910.idc.ecr.ap-south-1.amazonaws.com
        repositoryPath: payment-management
        tag: v1.0.1
serviceAccountName: payments
